import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
const Jbrrains = JetBrains_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokemon Grid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Jbrrains.className}
      >
          {children}
      </body>
    </html>
  );
}
